USE ROLE ACCOUNTADMIN;

USE DATABASE SALES_ANALYTICS_2025;

USE SCHEMA PUBLIC;

CREATE
OR REPLACE SECRET GITHUB_SECRET TYPE = password USERNAME = 'RajkumarManala1' PASSWORD = 'GITHUB_PERSONAL_ACCESS_TOKEN';
SHOW SECRETS;

CREATE
OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION API_PROVIDER = git_https_api API_ALLOWED_PREFIXES = ('https://github.com/RajkumarManala1/') ALLOWED_AUTHENTICATION_SECRETS = (SALES_ANALYTICS_2025.PUBLIC.GITHUB_SECRET) ENABLED = TRUE;

CREATE
OR REPLACE GIT REPOSITORY SALES_ANALYTICS_2025.PUBLIC.BICYCLE_SALES_REPO API_INTEGRATION = GITHUB_API_INTEGRATION GIT_CREDENTIALS = SALES_ANALYTICS_2025.PUBLIC.GITHUB_SECRET ORIGIN = 'https://github.com/RajkumarManala1/Bicycle-Sales-Analytics.git';

ALTER GIT REPOSITORY BICYCLE_SALES_REPO FETCH;SALES_ANALYTICS_2025.TRANSFORMED_DATA

SHOW GIT BRANCHES IN BICYCLE_SALES_REPO;